[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[functions]
  directory = "netlify/functions"

# Schedule the function to run every hour at minute 5
[functions.scheduledPost]
  schedule = "5 * * * *"

# Uncomment to use this redirect for Single Page Applications like create-react-app.
# Not needed for static site generators.
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

# Add environment variables if needed
#[functions.environment]
#  MY_ENV_VAR = "value"
