[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[functions]
  directory = "netlify/functions"

# Schedule the function to run every hour
[functions.scheduledPost]
  schedule = "@hourly"

# Schedule the notifyUpcomingEvents function to run daily at midnight
[functions.notifyUpcomingEvents]
  schedule = "0 0 * * *"